from enum import StrEnum

class DisabilityTypeEnum(StrEnum):
    VISION = "VISION"
    HEARING = "HEARING"
    MOBILITY = "MOBILITY"
    COGNITION = "COGNITION"
    SELF_CARE = "SELF_CARE"
    COMMUNICATION = "COMMUNICATION"


class DisabilitySeverityEnum(StrEnum):
    NO_DIFFICULTY = "NO_DIFFICULTY"
    SOME_DIFFICULTY = "SOME_DIFFICULTY"
    A_LOT_OF_DIFFICULTY = "A_LOT_OF_DIFFICULTY"
    CANNOT_DO_AT_ALL = "CANNOT_DO_AT_ALL"


class LanguageSpokenEnum(StrEnum):
    ENGLISH = "ENGLISH"
    HINDI = "HINDI"
    SPANISH = "SPANISH"
    FRENCH = "FRENCH"


class SourceOfIncomeEnum(StrEnum):
    # Master Data's SOURCE_OF_INCOME codes (agriculture domain), SOI_-prefixed.
    SOI_CROP_PRODUCTION = "SOI_CROP_PRODUCTION"
    SOI_LIVESTOCK_PRODUCTION = "SOI_LIVESTOCK_PRODUCTION"
    SOI_GOVERNMENT_NGO_SUPPORT = "SOI_GOVERNMENT_NGO_SUPPORT"
    SOI_OTHERS = "SOI_OTHERS"


class LandOwnershipTypeEnum(StrEnum):
    OWNER = "OWNER"
    TENANT = "TENANT"
    CROP_SHARE = "CROP_SHARE"


class LandSizeUnitEnum(StrEnum):
    HECTARE = "HECTARE"
    ACRE = "ACRE"
    SQUARE_METER = "SQUARE_METER"
    SQUARE_KM = "SQUARE_KM"
    SQUARE_FOOT = "SQUARE_FOOT"
    SQUARE_YARD = "SQUARE_YARD"


class CurrentLandUseEnum(StrEnum):
    AGRICULTURAL = "AGRICULTURAL"
    RESIDENTIAL = "RESIDENTIAL"
    GRAZING = "GRAZING"
    FOREST = "FOREST"


class FarmingTypeEnum(StrEnum):
    CROP = "CROP"
    LIVESTOCK = "LIVESTOCK"
    MIXED = "MIXED"
    AQUACULTURE = "AQUACULTURE"
    AGROFORESTRY = "AGROFORESTRY"


class LivestockSystemEnum(StrEnum):
    NOMADIC_PASTORAL = "NOMADIC_PASTORAL"
    SEMI_NOMADIC = "SEMI_NOMADIC"
    SEDENTARY_PASTORAL = "SEDENTARY_PASTORAL"
    MIXED = "MIXED"
    INDUSTRIAL = "INDUSTRIAL"


class FarmerClusterRoleEnum(StrEnum):
    LEAD = "LEAD"
    DEPUTY = "DEPUTY"
    SECRETARY = "SECRETARY"
    ACCOUNTANT = "ACCOUNTANT"
    MEMBER = "MEMBER"

class EducationalLevelEnum(StrEnum):
    ILLITERATE = "ILLITERATE"
    CAN_READ_AND_WRITE = "CAN_READ_AND_WRITE"
    BASIC = "BASIC"
    INTERMEDIARY = "INTERMEDIARY"
    HIGHER_EDUCATION = "HIGHER_EDUCATION"
    # Also in Master Data's EDUCATION_LEVEL list, which the dropdown now reads.
    NON_FORMAL = "NON_FORMAL"
    NEVER_ATTEND = "NEVER_ATTEND"
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    TERTIARY = "TERTIARY"
