-- Default values for this registry's code lists.
--
-- Generated from the option arrays that used to live inside the widgets. They
-- are DEFAULTS, not a definition: load_attributes_from_mds replaces any list the
-- country pack also defines, and an admin can edit them in the staff portal.
-- Before this the same values were compiled into g2p_register_sections, where
-- neither route could reach them.
--
-- Values are unchanged from what the widgets carried, so a deployment with no
-- country pack behaves exactly as it did.

INSERT INTO "public"."g2p_attribute_values" ("value_id","attribute_id","value_code","value_display","parent_value_id","sort_order") VALUES 
('DISABILITY_DOMAIN:VISION','DISABILITY_DOMAIN','VISION','VISION',NULL,1),
('DISABILITY_DOMAIN:HEARING','DISABILITY_DOMAIN','HEARING','HEARING',NULL,2),
('DISABILITY_DOMAIN:MOBILITY','DISABILITY_DOMAIN','MOBILITY','MOBILITY',NULL,3),
('DISABILITY_DOMAIN:COGNITION','DISABILITY_DOMAIN','COGNITION','COGNITION',NULL,4),
('DISABILITY_DOMAIN:SELF_CARE','DISABILITY_DOMAIN','SELF_CARE','SELF_CARE',NULL,5),
('DISABILITY_DOMAIN:COMMUNICATION','DISABILITY_DOMAIN','COMMUNICATION','COMMUNICATION',NULL,6),
('DISABILITY_SEVERITY:NO_DIFFICULTY','DISABILITY_SEVERITY','NO_DIFFICULTY','NO_DIFFICULTY',NULL,1),
('DISABILITY_SEVERITY:SOME_DIFFICULTY','DISABILITY_SEVERITY','SOME_DIFFICULTY','SOME_DIFFICULTY',NULL,2),
('DISABILITY_SEVERITY:A_LOT_OF_DIFFICULTY','DISABILITY_SEVERITY','A_LOT_OF_DIFFICULTY','A_LOT_OF_DIFFICULTY',NULL,3),
('DISABILITY_SEVERITY:CANNOT_DO_AT_ALL','DISABILITY_SEVERITY','CANNOT_DO_AT_ALL','CANNOT_DO_AT_ALL',NULL,4),
('EDUCATION_LEVEL:ILLITERATE','EDUCATION_LEVEL','ILLITERATE','ILLITERATE',NULL,1),
('EDUCATION_LEVEL:CAN_READ_AND_WRITE','EDUCATION_LEVEL','CAN_READ_AND_WRITE','CAN_READ_AND_WRITE',NULL,2),
('EDUCATION_LEVEL:BASIC','EDUCATION_LEVEL','BASIC','BASIC',NULL,3),
('EDUCATION_LEVEL:INTERMEDIARY','EDUCATION_LEVEL','INTERMEDIARY','INTERMEDIARY',NULL,4),
('EDUCATION_LEVEL:HIGHER_EDUCATION','EDUCATION_LEVEL','HIGHER_EDUCATION','HIGHER_EDUCATION',NULL,5),
('FARMER_CLUSTER_ROLE:LEAD','FARMER_CLUSTER_ROLE','LEAD','LEAD',NULL,1),
('FARMER_CLUSTER_ROLE:DEPUTY','FARMER_CLUSTER_ROLE','DEPUTY','DEPUTY',NULL,2),
('FARMER_CLUSTER_ROLE:SECRETARY','FARMER_CLUSTER_ROLE','SECRETARY','SECRETARY',NULL,3),
('FARMER_CLUSTER_ROLE:ACCOUNTANT','FARMER_CLUSTER_ROLE','ACCOUNTANT','ACCOUNTANT',NULL,4),
('FARMER_CLUSTER_ROLE:MEMBER','FARMER_CLUSTER_ROLE','MEMBER','MEMBER',NULL,5),
('GENDER:MALE','GENDER','MALE','MALE',NULL,1),
('GENDER:FEMALE','GENDER','FEMALE','FEMALE',NULL,2),
('GENDER:OTHERS','GENDER','OTHERS','OTHERS',NULL,3),
('GENDER:UNKNOWN','GENDER','UNKNOWN','UNKNOWN',NULL,4),
('MARITAL_STATUS:SINGLE','MARITAL_STATUS','SINGLE','SINGLE',NULL,1),
('MARITAL_STATUS:MARRIED','MARITAL_STATUS','MARRIED','MARRIED',NULL,2),
('MARITAL_STATUS:DIVORCED','MARITAL_STATUS','DIVORCED','DIVORCED',NULL,3),
('MARITAL_STATUS:WIDOWED','MARITAL_STATUS','WIDOWED','WIDOWED',NULL,4),
('MARITAL_STATUS:SEPARATED','MARITAL_STATUS','SEPARATED','SEPARATED',NULL,5),
('MARITAL_STATUS:UNKNOWN','MARITAL_STATUS','UNKNOWN','UNKNOWN',NULL,6),
('SOURCE_OF_INCOME:CROP_PRODUCTION','SOURCE_OF_INCOME','CROP_PRODUCTION','CROP_PRODUCTION',NULL,1),
('SOURCE_OF_INCOME:LIVESTOCK_PRODUCTION','SOURCE_OF_INCOME','LIVESTOCK_PRODUCTION','LIVESTOCK_PRODUCTION',NULL,2),
('SOURCE_OF_INCOME:GOVERNMENT_NGO_SUPPORT','SOURCE_OF_INCOME','GOVERNMENT_NGO_SUPPORT','GOVERNMENT_NGO_SUPPORT',NULL,3),
('SOURCE_OF_INCOME:OTHERS','SOURCE_OF_INCOME','OTHERS','OTHERS',NULL,4),
('PREFIX_MR','PREFIX','MR','MR',NULL,1),
('PREFIX_MRS','PREFIX','MRS','MRS',NULL,2),
('PREFIX_MISS','PREFIX','MISS','MISS',NULL,3),
('REL_HEAD_CHILD','RELATIONSHIP_TO_THE_HEAD','CHILD','CHILD',NULL,1),
('REL_HEAD_SPOUSE','RELATIONSHIP_TO_THE_HEAD','SPOUSE','SPOUSE',NULL,2),
('REL_HEAD_OTHER','RELATIONSHIP_TO_THE_HEAD','OTHER','OTHER',NULL,3)
ON CONFLICT (value_id) DO NOTHING;
